# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
before_install:
- gem install cocoapods --quiet
- pod --version
script:
- xctool test -workspace Example/MUKDataSource.xcworkspace -scheme MUKDataSource -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
notifications:
  email: false
